import type { Metadata } from "next";
import { Orbitron, Tomorrow, Quantico, Major_Mono_Display, Spectral, Agdasima } from "next/font/google";
import "./globals.css";

const OrbitronFont = Orbitron({
  subsets: ["latin"],
  weight: ["400", "500", "700", "900"],
  variable: "--font-orbitron",
  display: "swap",
});

const TomorrowFont = Tomorrow({
  subsets: ["latin"],
  weight: ["400", "500", "700", "900"],
  variable: "--font-tomorrow",
  display: "swap",
});

const QuanticoFont = Quantico({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-quantico",
  display: "swap",
});

const MajorMonoDisplayFont = Major_Mono_Display({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-major-mono-display",
  display: "swap",
});

const SpectralFont = Spectral({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-spectral",
  display: "swap",
});

const AgdasimaFont = Agdasima({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-agdasima",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Wortex Studio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`    
          ${OrbitronFont.variable}
          ${TomorrowFont.variable}
          ${QuanticoFont.variable}
          ${MajorMonoDisplayFont.variable}
          ${SpectralFont.variable}
          ${AgdasimaFont.variable}
          antialiased
          `}
      >
        {children}
      </body>
    </html>
  );
}
